apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build: 
  local:
    push: false
  artifacts:
    - image: tmonaco/client
      context: client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: 'src/**/*.jsx'
            dest: .
          - src: 'src/**/*.js'
            dest: .
    - image: tmonaco/comments
      context: comments
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tmonaco/event-bus
      context: event-bus
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tmonaco/moderation
      context: moderation
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tmonaco/posts
      context: posts
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .
    - image: tmonaco/query
      context: query
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual:
          - src: '*.js'
            dest: .